## Setting up SQL interface with Jupyter Lab ##

In [1]:
%load_ext sql

Data source:

https://www.kaggle.com/alexgude/california-traffic-collision-data-from-switrs

Loading the files:

In [2]:
%sql sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite

## Exploring the data ##

View variables in the collisions and parties tables

In [16]:
%sql PRAGMA table_info(collisions);

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(0, 'case_id', 'TEXT', 0, None, 0),
 (1, 'jurisdiction', 'INT', 0, None, 0),
 (2, 'officer_id', 'TEXT', 0, None, 0),
 (3, 'reporting_district', 'TEXT', 0, None, 0),
 (4, 'chp_shift', 'TEXT', 0, None, 0),
 (5, 'population', 'TEXT', 0, None, 0),
 (6, 'county_city_location', 'TEXT', 0, None, 0),
 (7, 'special_condition', 'TEXT', 0, None, 0),
 (8, 'beat_type', 'TEXT', 0, None, 0),
 (9, 'chp_beat_type', 'TEXT', 0, None, 0),
 (10, 'city_division_lapd', 'TEXT', 0, None, 0),
 (11, 'chp_beat_class', 'TEXT', 0, None, 0),
 (12, 'beat_number', 'TEXT', 0, None, 0),
 (13, 'primary_road', 'TEXT', 0, None, 0),
 (14, 'secondary_road', 'TEXT', 0, None, 0),
 (15, 'distance', 'REAL', 0, None, 0),
 (16, 'direction', 'TEXT', 0, None, 0),
 (17, 'intersection', 'INT', 0, None, 0),
 (18, 'weather_1', 'TEXT', 0, None, 0),
 (19, 'weather_2', 'TEXT', 0, None, 0),
 (20, 'state_highway_indicator', 'INT', 0, None, 0),
 (21, 'caltrans_county', 'TEXT', 0, None, 0),
 (22, 'caltrans_district', 'INT', 0, None, 0),
 (23, 'state_route', 'INT', 0, None, 0),
 (24, 'route_suffix', 'TEXT', 0, None, 0),
 (25, 'postmile_prefix', 'TEXT', 0, None, 0),
 (26, 'postmile', 'REAL', 0, None, 0),
 (27, 'location_type', 'TEXT', 0, None, 0),
 (28, 'ramp_intersection', 'INT', 0, None, 0),
 (29, 'side_of_highway', 'TEXT', 0, None, 0),
 (30, 'tow_away', 'INT', 0, None, 0),
 (31, 'collision_severity', 'TEXT', 0, None, 0),
 (32, 'killed_victims', 'INT', 0, None, 0),
 (33, 'injured_victims', 'INT', 0, None, 0),
 (34, 'party_count', 'INT', 0, None, 0),
 (35, 'primary_collision_factor', 'TEXT', 0, None, 0),
 (36, 'pcf_violation_code', 'TEXT', 0, None, 0),
 (37, 'pcf_violation_category', 'TEXT', 0, None, 0),
 (38, 'pcf_violation', 'INT', 0, None, 0),
 (39, 'pcf_violation_subsection', 'TEXT', 0, None, 0),
 (40, 'hit_and_run', 'TEXT', 0, None, 0),
 (41, 'type_of_collision', 'TEXT', 0, None, 0),
 (42, 'motor_vehicle_involved_with', 'TEXT', 0, None, 0),
 (43, 'pedestrian_action', 'TEXT', 0, None, 0),
 (44, 'road_surface', 'TEXT', 0, None, 0),
 (45, 'road_condition_1', 'TEXT', 0, None, 0),
 (46, 'road_condition_2', 'TEXT', 0, None, 0),
 (47, 'lighting', 'TEXT', 0, None, 0),
 (48, 'control_device', 'TEXT', 0, None, 0),
 (49, 'chp_road_type', 'TEXT', 0, None, 0),
 (50, 'pedestrian_collision', 'INT', 0, None, 0),
 (51, 'bicycle_collision', 'INT', 0, None, 0),
 (52, 'motorcycle_collision', 'INT', 0, None, 0),
 (53, 'truck_collision', 'INT', 0, None, 0),
 (54, 'not_private_property', 'INT', 0, None, 0),
 (55, 'alcohol_involved', 'INT', 0, None, 0),
 (56, 'statewide_vehicle_type_at_fault', 'TEXT', 0, None, 0),
 (57, 'chp_vehicle_type_at_fault', 'TEXT', 0, None, 0),
 (58, 'severe_injury_count', 'INT', 0, None, 0),
 (59, 'other_visible_injury_count', 'INT', 0, None, 0),
 (60, 'complaint_of_pain_injury_count', 'INT', 0, None, 0),
 (61, 'pedestrian_killed_count', 'INT', 0, None, 0),
 (62, 'pedestrian_injured_count', 'INT', 0, None, 0),
 (63, 'bicyclist_killed_count', 'INT', 0, None, 0),
 (64, 'bicyclist_injured_count', 'INT', 0, None, 0),
 (65, 'motorcyclist_killed_count', 'INT', 0, None, 0),
 (66, 'motorcyclist_injured_count', 'INT', 0, None, 0),
 (67, 'primary_ramp', 'TEXT', 0, None, 0),
 (68, 'secondary_ramp', 'TEXT', 0, None, 0),
 (69, 'latitude', 'REAL', 0, None, 0),
 (70, 'longitude', 'REAL', 0, None, 0),
 (71, 'collision_date', 'TEXT', 0, None, 0),
 (72, 'collision_time', 'TEXT', 0, None, 0),
 (73, 'process_date', 'TEXT', 0, None, 0)]

In [38]:
%sql PRAGMA table_info(parties);

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(0, 'id', 'INT', 0, None, 0),
 (1, 'case_id', 'TEXT', 0, None, 0),
 (2, 'party_number', 'INT', 0, None, 0),
 (3, 'party_type', 'TEXT', 0, None, 0),
 (4, 'at_fault', 'INT', 0, None, 0),
 (5, 'party_sex', 'TEXT', 0, None, 0),
 (6, 'party_age', 'INT', 0, None, 0),
 (7, 'party_sobriety', 'TEXT', 0, None, 0),
 (8, 'party_drug_physical', 'TEXT', 0, None, 0),
 (9, 'direction_of_travel', 'TEXT', 0, None, 0),
 (10, 'party_safety_equipment_1', 'TEXT', 0, None, 0),
 (11, 'party_safety_equipment_2', 'TEXT', 0, None, 0),
 (12, 'financial_responsibility', 'TEXT', 0, None, 0),
 (13, 'hazardous_materials', 'TEXT', 0, None, 0),
 (14, 'cellphone_use', 'TEXT', 0, None, 0),
 (15, 'school_bus_related', 'TEXT', 0, None, 0),
 (16, 'oaf_violation_code', 'TEXT', 0, None, 0),
 (17, 'oaf_violation_category', 'TEXT', 0, None, 0),
 (18, 'oaf_violation_section', 'INT', 0, None, 0),
 (19, 'oaf_violation_suffix', 'TEXT', 0, None, 0),
 (20, 'other_associate_factor_1', 'TEXT', 0, None, 0),
 (21, 'other_associate_factor_2', 'TEXT', 0, None, 0),
 (22, 'party_number_killed', 'INT', 0, None, 0),
 (23, 'party_number_injured', 'INT', 0, None, 0),
 (24, 'movement_preceding_collision', 'TEXT', 0, None, 0),
 (25, 'vehicle_year', 'INT', 0, None, 0),
 (26, 'vehicle_make', 'TEXT', 0, None, 0),
 (27, 'statewide_vehicle_type', 'TEXT', 0, None, 0),
 (28, 'chp_vehicle_type_towing', 'TEXT', 0, None, 0),
 (29, 'chp_vehicle_type_towed', 'TEXT', 0, None, 0),
 (30, 'party_race', 'TEXT', 0, None, 0)]

How many cyclist crashes happen each year?

What percentage of cycling collisions resulted in injury or fatality by year?

In [8]:
%sql SELECT strftime('%Y', collision_date) AS year, \
SUM(bicycle_collision), \
ROUND(SUM(killed_victims) * 1.0 / SUM(bicycle_collision), 4) AS rate_fatalities, \
ROUND(SUM(injured_victims) * 1.0 / SUM(bicycle_collision), 4) AS rate_injuries \
FROM collisions \
WHERE bicycle_collision = 1 AND Collision_Date <= '2020-12-31' \
GROUP BY year \
ORDER BY rate_fatalities;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[('2010', 13966, 0.0079, 0.933),
 ('2009', 13445, 0.0081, 0.9186),
 ('2011', 15041, 0.0094, 0.9288),
 ('2001', 12720, 0.0096, 0.9211),
 ('2002', 12355, 0.0097, 0.9166),
 ('2004', 12452, 0.01, 0.9162),
 ('2012', 15276, 0.01, 0.9363),
 ('2008', 13079, 0.0101, 0.9238),
 ('2014', 14285, 0.0101, 0.94),
 ('2003', 12204, 0.0104, 0.9168),
 ('2007', 11781, 0.0106, 0.9234),
 ('2005', 11731, 0.0113, 0.9205),
 ('2013', 14542, 0.0113, 0.9385),
 ('2015', 13958, 0.0113, 0.9327),
 ('2020', 5418, 0.0129, 0.9247),
 ('2006', 10975, 0.0132, 0.9223),
 ('2017', 12398, 0.0132, 0.9254),
 ('2016', 13039, 0.0133, 0.9235),
 ('2019', 11192, 0.0138, 0.927),
 ('2018', 12166, 0.0147, 0.9225)]

The deadliest year for bicycle collisions (in terms of the rate of fatalities) was 2018. Most collisions (> 90%) result in injury, but that's likely due to bias of the dataset. The police are more likely to be notified when accidents are more severe.

Compare totals for collisions and parties tables

In [4]:
%sql select sum(collisions.bicycle_collision), \
(select count(parties.party_type) \
from parties \
where party_type = 'bicyclist') as sum_party_type \
from collisions;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(252023, 256305)]

Since the number of bicycle collisions is less than the number of parties involving bicyclists, it seems like over 4,000 collisions since 2001 involved more than one cyclist.

How many crashes involved bicycles but no cars?

In [31]:
#collisions with motor vehicle and bicycle:

%sql SELECT COUNT(*) FROM collisions \
        WHERE motor_vehicle_involved_with = 'bicycle';

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(222476,)]

In [27]:
# number of all bike collisions minus collisions with bike and motor vehicle

%sql SELECT \
    (SELECT SUM(bicycle_collision) FROM collisions) - \
    (SELECT COUNT(*) FROM collisions \
        WHERE motor_vehicle_involved_with = 'bicycle') as bike_no_car;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(29547,)]

In [32]:
# view examples of bike_no_car

%sql SELECT * FROM collisions \
        WHERE bicycle_collision = 1 AND \
        motor_vehicle_involved_with != 'bicycle' \
        Limit 5;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[('3526265', 5600, '3364', None, '5', '6', '5607', '0', '0', 'not chp', None, 'not chp', None, 'THOUSAND OAKS BL', 'MAEGAN PL', 2.0, 'west', 0, 'clear', None, 0, None, None, None, None, None, None, None, None, None, 1, 'pain', 0, 1, 2, 'vehicle code violation', None, 'dui', 23152, 'A', 'not hit and run', 'hit object', 'fixed object', 'no pedestrian involved', 'dry', 'normal', None, 'dark with street lights', 'none', '0', None, 1, None, None, 1, 1, 'passenger car', '01', 0, 0, 1, 0, 0, 0, 1, 0, 0, None, None, None, None, '2008-01-03', '17:50:00', '2008-08-13'),
 ('3526312', 3009, '9207', '136', '5', '6', '3009', '0', '0', 'not chp', None, 'not chp', '00R', 'HARBOR BL', 'QUATRO AV', 345.0, 'north', 0, 'clear', None, 0, None, None, None, None, None, None, None, None, None, 1, 'other injury', 0, 1, 7, 'vehicle code violation', None, 'dui', 23152, 'A', 'not hit and run', 'rear end', 'other motor vehicle', 'no pedestrian involved', 'dry', 'normal', None, 'dark with street lights', 'obscured', '0', None, 1, None, None, 1, 1, 'passenger car', '01', 0, 1, 0, 0, 0, 0, 1, 0, 0, None, None, None, None, '2008-01-01', '00:40:00', '2008-08-14'),
 ('3560150', 4316, '10329', '28', '5', '6', '4316', '0', '0', 'not chp', None, 'not chp', '002', 'CENTRAL EXPWY', 'FAIROAKS AV', 528.0, 'west', 0, 'cloudy', None, 0, None, None, None, None, None, None, None, None, None, 0, 'other injury', 0, 1, 1, 'vehicle code violation', None, 'speeding', 22350, None, 'not hit and run', 'hit object', 'fixed object', 'no pedestrian involved', 'wet', 'normal', None, 'daylight', 'none', '0', None, 1, None, None, 1, None, 'bicycle', '04', 0, 1, 0, 0, 0, 0, 1, 0, 0, None, None, None, None, '2008-01-10', '15:42:00', '2008-08-11'),
 ('3565150', 3019, '1839', None, '5', '7', '3019', '0', '0', 'not chp', None, 'not chp', None, 'SUNFLOWER AV', 'FAIRVIEW RD', 0.0, None, 1, 'clear', None, 0, None, None, None, None, None, None, None, None, None, 0, 'pain', 0, 1, 2, 'vehicle code violation', None, 'traffic signals and signs', 21453, 'A', 'not hit and run', 'pedestrian', 'other motor vehicle', 'no pedestrian involved', 'dry', 'normal', None, 'daylight', 'functioning', '0', None, 1, None, None, 1, None, None, None, 0, 0, 1, 0, 0, 0, 1, 0, 0, None, None, None, None, '2008-01-01', '09:28:00', '2008-08-11'),
 ('3565192', 5001, '627', None, '5', '4', '5001', '0', '0', 'not chp', None, 'not chp', '001', 'RICHLAND AV', 'HATCH RD', 0.0, None, 1, 'cloudy', 'raining', 0, None, None, None, None, None, None, None, None, None, 0, 'pain', 0, 1, 2, 'vehicle code violation', None, 'traffic signals and signs', 21453, 'A', 'felony', 'broadside', 'pedestrian', 'no pedestrian involved', 'wet', 'normal', None, 'daylight', 'functioning', '0', None, 1, None, None, 1, 1, 'passenger car', None, 0, 0, 1, 0, 0, 0, 1, 0, 0, None, None, None, None, '2008-01-10', '08:13:00', '2008-08-13')]

On what days of the week do most bicycle collisions occur?

In [27]:
%sql SELECT SUM(bicycle_collision), \
    CASE WHEN strftime('%w', collision_date) = '0' THEN 'Sunday' \
    WHEN strftime('%w', collision_date) = '1' THEN 'Monday' \
    WHEN strftime('%w', collision_date) = '2' THEN 'Tuesday' \
    WHEN strftime('%w', collision_date) = '3' THEN 'Wednesday' \
    WHEN strftime('%w', collision_date) = '4' THEN 'Thursday' \
    WHEN strftime('%w', collision_date) = '5' THEN 'Friday' \
    ELSE 'Saturday' END AS day_of_week \
from collisions \
WHERE bicycle_collision = 1 AND Collision_Date <= '2020-12-31' \
GROUP BY day_of_week \
ORDER BY SUM(bicycle_collision) DESC;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(40133, 'Wednesday'),
 (39969, 'Tuesday'),
 (39571, 'Thursday'),
 (39169, 'Friday'),
 (36594, 'Monday'),
 (31174, 'Saturday'),
 (25413, 'Sunday')]

During which months of the year do most bicycle collisions occur?

In [29]:
%sql SELECT SUM(bicycle_collision), \
    CASE WHEN strftime('%m', collision_date) = '01' THEN 'Jan' \
    WHEN strftime('%m', collision_date) = '02' THEN 'Feb' \
    WHEN strftime('%m', collision_date) = '03' THEN 'Mar' \
    WHEN strftime('%m', collision_date) = '04' THEN 'Apr' \
    WHEN strftime('%m', collision_date) = '05' THEN 'May' \
    WHEN strftime('%m', collision_date) = '06' THEN 'Jun' \
    WHEN strftime('%m', collision_date) = '07' THEN 'Jul' \
    WHEN strftime('%m', collision_date) = '08' THEN 'Aug' \
    WHEN strftime('%m', collision_date) = '09' THEN 'Sep' \
    WHEN strftime('%m', collision_date) = '10' THEN 'Oct' \
    WHEN strftime('%m', collision_date) = '11' THEN 'Nov' \
    ELSE 'Dec' END AS day_of_week \
from collisions \
WHERE bicycle_collision = 1 AND Collision_Date <= '2020-12-31' \
GROUP BY day_of_week \
ORDER BY SUM(bicycle_collision) DESC;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(24849, 'Sep'),
 (24205, 'Oct'),
 (23636, 'Jul'),
 (23443, 'Aug'),
 (23130, 'May'),
 (22992, 'Jun'),
 (20906, 'Apr'),
 (20348, 'Mar'),
 (18933, 'Nov'),
 (17210, 'Feb'),
 (17188, 'Jan'),
 (15183, 'Dec')]

What types of weather conditions correlate with bicycle collisions?

In [37]:
%sql SELECT weather_1, \
SUM(bicycle_collision) \
FROM collisions \
WHERE bicycle_collision = 1 AND Collision_Date <= '2020-12-31' \
GROUP BY weather_1 \
ORDER BY SUM(bicycle_collision) DESC;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[('clear', 222256),
 ('cloudy', 23463),
 ('raining', 3661),
 (None, 1768),
 ('fog', 482),
 ('other', 272),
 ('wind', 81),
 ('snowing', 40)]

Unsurprisingly, the fewest accidents occur on snowy days, probably because fewer people are cycling then. Similarly, more people are out on clear days and in warmer months, increasing the chances of collision.

How often are cyclists the party at fault in collisions each year?

In [32]:
#ctes

%sql WITH cte as ( \
    SELECT strftime('%Y', collision_date) AS year, \
    SUM(bicycle_collision) AS n_bike_collisions \
    FROM collisions \
    WHERE bicycle_collision = 1 AND Collision_Date <= '2020-12-31' \
    GROUP BY year) \
SELECT strftime('%Y', collision_date) AS year, \
    SUM(bicycle_collision), \
    ROUND(SUM(bicycle_collision) * 1.0 / 13966, 4) AS rate_bike_fault, \
    AVG(cte.n_bike_collisions) \
FROM collisions \
INNER JOIN parties \
ON collisions.case_id = parties.case_id \
WHERE at_fault = 1 and \
    statewide_vehicle_type = 'bicycle' and \
    bicycle_collision = 1 AND \
    Collision_Date <= '2020-12-31'\
GROUP BY year;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
(sqlite3.OperationalError) no such column: cte.n_bike_collisions
[SQL: WITH cte as ( SELECT strftime('%Y', collision_date) AS year, SUM(bicycle_collision) AS n_bike_collisions FROM collisions WHERE bicycle_collision = 1 AND Collision_Date <= '2020-12-31' GROUP BY year) SELECT strftime('%Y', collision_date) AS year, SUM(bicycle_collision), ROUND(SUM(bicycle_collision) * 1.0 / 13966, 4) AS rate_bike_fault, AVG(cte.n_bike_collisions) FROM collisions INNER JOIN parties ON collisions.case_id = parties.case_id WHERE at_fault = 1 and statewide_vehicle_type = 'bicycle' and bicycle_collision = 1 AND Collision_Date <= '2020-12-31' GROUP BY year;]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

In [8]:
#subquery in select

%sql SELECT strftime('%Y', collision_date) AS year, \
    SUM(bicycle_collision), \
    ROUND(SUM(bicycle_collision) * 1.0 / 13966, 4) AS rate_bike_fault, \
    (SELECT SUM(bicycle_collision) AS n_bike_collisions \
    FROM collisions \
    WHERE bicycle_collision = 1 AND Collision_Date <= '2020-12-31') as n_bike_collisions \
FROM collisions \
INNER JOIN parties \
ON collisions.case_id = parties.case_id \
WHERE at_fault = 1 and \
    statewide_vehicle_type = 'bicycle' and \
    bicycle_collision = 1 AND \
    Collision_Date <= '2020-12-31'\
GROUP BY year;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[('2001', 7568, 0.5419, 252023),
 ('2002', 5945, 0.4257, 252023),
 ('2003', 6406, 0.4587, 252023),
 ('2004', 7192, 0.515, 252023),
 ('2005', 6656, 0.4766, 252023),
 ('2006', 6064, 0.4342, 252023),
 ('2007', 6601, 0.4726, 252023),
 ('2008', 7312, 0.5236, 252023),
 ('2009', 7556, 0.541, 252023),
 ('2010', 7931, 0.5679, 252023),
 ('2011', 8643, 0.6189, 252023),
 ('2012', 8823, 0.6317, 252023),
 ('2013', 8204, 0.5874, 252023),
 ('2014', 7845, 0.5617, 252023),
 ('2015', 7530, 0.5392, 252023),
 ('2016', 7040, 0.5041, 252023),
 ('2017', 6631, 0.4748, 252023),
 ('2018', 6519, 0.4668, 252023),
 ('2019', 5893, 0.422, 252023),
 ('2020', 2842, 0.2035, 252023)]

In [43]:
#subquery in from

%sql SELECT strftime('%Y', collision_date) AS year, \
    SUM(bicycle_collision), \
    ROUND(SUM(bicycle_collision) * 1.0 / 13966, 4) AS rate_bike_fault \
FROM (SELECT strftime('%Y', collision_date) AS year, \
         SUM(bicycle_collision) \
    FROM collisions \
    WHERE bicycle_collision = 1 AND Collision_Date <= '2020-12-31' \
    GROUP BY year) as sub    \
INNER JOIN parties \
ON collisions.case_id = parties.case_id \
WHERE at_fault = 1 and \
    statewide_vehicle_type = 'bicycle' and \
    bicycle_collision = 1 AND \
    Collision_Date <= '2020-12-31'\
GROUP BY year;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
(sqlite3.OperationalError) no such column: collision_date
[SQL: SELECT strftime('%Y', collision_date) AS year, SUM(bicycle_collision), ROUND(SUM(bicycle_collision) * 1.0 / 13966, 4) AS rate_bike_fault FROM (SELECT strftime('%Y', collision_date) AS year, SUM(bicycle_collision) FROM collisions WHERE bicycle_collision = 1 AND Collision_Date <= '2020-12-31' GROUP BY year) as sub INNER JOIN parties ON collisions.case_id = parties.case_id WHERE at_fault = 1 and statewide_vehicle_type = 'bicycle' and bicycle_collision = 1 AND Collision_Date <= '2020-12-31' GROUP BY year;]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

In [25]:
# over partition

%sql SELECT strftime('%Y', collision_date) AS year, \
    SUM(bicycle_collision), \
    AVG(bicycle_collision) OVER(PARTITION BY strftime('%Y', collision_date)) AS year_sum \
FROM collisions \
INNER JOIN parties \
ON collisions.case_id = parties.case_id \
WHERE at_fault = 1 and \
    statewide_vehicle_type = 'bicycle' and \
    bicycle_collision = 1 AND \
    Collision_Date <= '2020-12-31'\
GROUP BY year;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[('2001', 7568, 1.0),
 ('2002', 5945, 1.0),
 ('2003', 6406, 1.0),
 ('2004', 7192, 1.0),
 ('2005', 6656, 1.0),
 ('2006', 6064, 1.0),
 ('2007', 6601, 1.0),
 ('2008', 7312, 1.0),
 ('2009', 7556, 1.0),
 ('2010', 7931, 1.0),
 ('2011', 8643, 1.0),
 ('2012', 8823, 1.0),
 ('2013', 8204, 1.0),
 ('2014', 7845, 1.0),
 ('2015', 7530, 1.0),
 ('2016', 7040, 1.0),
 ('2017', 6631, 1.0),
 ('2018', 6519, 1.0),
 ('2019', 5893, 1.0),
 ('2020', 2842, 1.0)]

**Oustanding questions**

How often are cyclists at fault?

Difference between the sexes? Party at fault or victim?

Differences between age groups? Party at fault or victim?