# Cycling Collisions in California #

In this project, I use Jupyter Notebooks and SQLite to analyze traffic collisions in California involving at least one bicycle.

The data has been requested and cleaned by Alex Gude and uploaded to Kaggle. The original data comes from the California Highway Patrol and covers collisions from January 1st, 2001 until mid-October, 2020.

## Setting up SQL interface with Jupyter Lab ##

In [2]:
%load_ext sql

Data source:

https://www.kaggle.com/alexgude/california-traffic-collision-data-from-switrs

Loading the files:

In [3]:
%sql sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite

## Exploring the data ##

View variables in the collisions, parties, and victims tables

In [16]:
%sql PRAGMA table_info(collisions);

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(0, 'case_id', 'TEXT', 0, None, 0),
 (1, 'jurisdiction', 'INT', 0, None, 0),
 (2, 'officer_id', 'TEXT', 0, None, 0),
 (3, 'reporting_district', 'TEXT', 0, None, 0),
 (4, 'chp_shift', 'TEXT', 0, None, 0),
 (5, 'population', 'TEXT', 0, None, 0),
 (6, 'county_city_location', 'TEXT', 0, None, 0),
 (7, 'special_condition', 'TEXT', 0, None, 0),
 (8, 'beat_type', 'TEXT', 0, None, 0),
 (9, 'chp_beat_type', 'TEXT', 0, None, 0),
 (10, 'city_division_lapd', 'TEXT', 0, None, 0),
 (11, 'chp_beat_class', 'TEXT', 0, None, 0),
 (12, 'beat_number', 'TEXT', 0, None, 0),
 (13, 'primary_road', 'TEXT', 0, None, 0),
 (14, 'secondary_road', 'TEXT', 0, None, 0),
 (15, 'distance', 'REAL', 0, None, 0),
 (16, 'direction', 'TEXT', 0, None, 0),
 (17, 'intersection', 'INT', 0, None, 0),
 (18, 'weather_1', 'TEXT', 0, None, 0),
 (19, 'weather_2', 'TEXT', 0, None, 0),
 (20, 'state_highway_indicator', 'INT', 0, None, 0),
 (21, 'caltrans_county', 'TEXT', 0, None, 0),
 (22, 'caltrans_district', 'INT', 0, None, 0),
 (23, 'state_route', 'INT', 0, None, 0),
 (24, 'route_suffix', 'TEXT', 0, None, 0),
 (25, 'postmile_prefix', 'TEXT', 0, None, 0),
 (26, 'postmile', 'REAL', 0, None, 0),
 (27, 'location_type', 'TEXT', 0, None, 0),
 (28, 'ramp_intersection', 'INT', 0, None, 0),
 (29, 'side_of_highway', 'TEXT', 0, None, 0),
 (30, 'tow_away', 'INT', 0, None, 0),
 (31, 'collision_severity', 'TEXT', 0, None, 0),
 (32, 'killed_victims', 'INT', 0, None, 0),
 (33, 'injured_victims', 'INT', 0, None, 0),
 (34, 'party_count', 'INT', 0, None, 0),
 (35, 'primary_collision_factor', 'TEXT', 0, None, 0),
 (36, 'pcf_violation_code', 'TEXT', 0, None, 0),
 (37, 'pcf_violation_category', 'TEXT', 0, None, 0),
 (38, 'pcf_violation', 'INT', 0, None, 0),
 (39, 'pcf_violation_subsection', 'TEXT', 0, None, 0),
 (40, 'hit_and_run', 'TEXT', 0, None, 0),
 (41, 'type_of_collision', 'TEXT', 0, None, 0),
 (42, 'motor_vehicle_involved_with', 'TEXT', 0, None, 0),
 (43, 'pedestrian_action', 'TEXT', 0, None, 0),
 (44, 'road_surface', 'TEXT', 0, None, 0),
 (45, 'road_condition_1', 'TEXT', 0, None, 0),
 (46, 'road_condition_2', 'TEXT', 0, None, 0),
 (47, 'lighting', 'TEXT', 0, None, 0),
 (48, 'control_device', 'TEXT', 0, None, 0),
 (49, 'chp_road_type', 'TEXT', 0, None, 0),
 (50, 'pedestrian_collision', 'INT', 0, None, 0),
 (51, 'bicycle_collision', 'INT', 0, None, 0),
 (52, 'motorcycle_collision', 'INT', 0, None, 0),
 (53, 'truck_collision', 'INT', 0, None, 0),
 (54, 'not_private_property', 'INT', 0, None, 0),
 (55, 'alcohol_involved', 'INT', 0, None, 0),
 (56, 'statewide_vehicle_type_at_fault', 'TEXT', 0, None, 0),
 (57, 'chp_vehicle_type_at_fault', 'TEXT', 0, None, 0),
 (58, 'severe_injury_count', 'INT', 0, None, 0),
 (59, 'other_visible_injury_count', 'INT', 0, None, 0),
 (60, 'complaint_of_pain_injury_count', 'INT', 0, None, 0),
 (61, 'pedestrian_killed_count', 'INT', 0, None, 0),
 (62, 'pedestrian_injured_count', 'INT', 0, None, 0),
 (63, 'bicyclist_killed_count', 'INT', 0, None, 0),
 (64, 'bicyclist_injured_count', 'INT', 0, None, 0),
 (65, 'motorcyclist_killed_count', 'INT', 0, None, 0),
 (66, 'motorcyclist_injured_count', 'INT', 0, None, 0),
 (67, 'primary_ramp', 'TEXT', 0, None, 0),
 (68, 'secondary_ramp', 'TEXT', 0, None, 0),
 (69, 'latitude', 'REAL', 0, None, 0),
 (70, 'longitude', 'REAL', 0, None, 0),
 (71, 'collision_date', 'TEXT', 0, None, 0),
 (72, 'collision_time', 'TEXT', 0, None, 0),
 (73, 'process_date', 'TEXT', 0, None, 0)]

In [38]:
%sql PRAGMA table_info(parties);

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(0, 'id', 'INT', 0, None, 0),
 (1, 'case_id', 'TEXT', 0, None, 0),
 (2, 'party_number', 'INT', 0, None, 0),
 (3, 'party_type', 'TEXT', 0, None, 0),
 (4, 'at_fault', 'INT', 0, None, 0),
 (5, 'party_sex', 'TEXT', 0, None, 0),
 (6, 'party_age', 'INT', 0, None, 0),
 (7, 'party_sobriety', 'TEXT', 0, None, 0),
 (8, 'party_drug_physical', 'TEXT', 0, None, 0),
 (9, 'direction_of_travel', 'TEXT', 0, None, 0),
 (10, 'party_safety_equipment_1', 'TEXT', 0, None, 0),
 (11, 'party_safety_equipment_2', 'TEXT', 0, None, 0),
 (12, 'financial_responsibility', 'TEXT', 0, None, 0),
 (13, 'hazardous_materials', 'TEXT', 0, None, 0),
 (14, 'cellphone_use', 'TEXT', 0, None, 0),
 (15, 'school_bus_related', 'TEXT', 0, None, 0),
 (16, 'oaf_violation_code', 'TEXT', 0, None, 0),
 (17, 'oaf_violation_category', 'TEXT', 0, None, 0),
 (18, 'oaf_violation_section', 'INT', 0, None, 0),
 (19, 'oaf_violation_suffix', 'TEXT', 0, None, 0),
 (20, 'other_associate_factor_1', 'TEXT', 0, None, 0),
 (21, 'other_associate_factor_2', 'TEXT', 0, None, 0),
 (22, 'party_number_killed', 'INT', 0, None, 0),
 (23, 'party_number_injured', 'INT', 0, None, 0),
 (24, 'movement_preceding_collision', 'TEXT', 0, None, 0),
 (25, 'vehicle_year', 'INT', 0, None, 0),
 (26, 'vehicle_make', 'TEXT', 0, None, 0),
 (27, 'statewide_vehicle_type', 'TEXT', 0, None, 0),
 (28, 'chp_vehicle_type_towing', 'TEXT', 0, None, 0),
 (29, 'chp_vehicle_type_towed', 'TEXT', 0, None, 0),
 (30, 'party_race', 'TEXT', 0, None, 0)]

In [26]:
%sql PRAGMA table_info(victims);

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(0, 'id', 'INT', 0, None, 0),
 (1, 'case_id', 'TEXT', 0, None, 0),
 (2, 'party_number', 'INT', 0, None, 0),
 (3, 'victim_role', 'TEXT', 0, None, 0),
 (4, 'victim_sex', 'TEXT', 0, None, 0),
 (5, 'victim_age', 'INT', 0, None, 0),
 (6, 'victim_degree_of_injury', 'TEXT', 0, None, 0),
 (7, 'victim_seating_position', 'TEXT', 0, None, 0),
 (8, 'victim_safety_equipment_1', 'TEXT', 0, None, 0),
 (9, 'victim_safety_equipment_2', 'TEXT', 0, None, 0),
 (10, 'victim_ejected', 'TEXT', 0, None, 0)]

How many cyclist crashes happen each year?

What percentage of cycling collisions resulted in injury or fatality by year?

In [21]:
%sql SELECT strftime('%Y', collision_date) AS year, \
SUM(bicycle_collision), \
SUM(killed_victims), \
SUM(bicyclist_killed_count), \
ROUND(SUM(bicyclist_killed_count) * 1.0 / SUM(bicycle_collision), 4) AS prop_bike_fatalities, \
SUM(injured_victims), \
SUM(bicyclist_injured_count), \
ROUND(SUM(bicyclist_injured_count) * 1.0 / SUM(bicycle_collision), 4) AS prop_bike_injured \
FROM collisions \
WHERE bicycle_collision = 1 AND Collision_Date <= '2020-12-31' \
GROUP BY year \
ORDER BY prop_bike_fatalities DESC;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[('2018', 12166, 179, 177, 0.0145, 11223, 10900, 0.8959),
 ('2019', 11192, 154, 153, 0.0137, 10375, 10069, 0.8997),
 ('2016', 13039, 173, 172, 0.0132, 12042, 11727, 0.8994),
 ('2017', 12398, 164, 162, 0.0131, 11473, 11148, 0.8992),
 ('2006', 10975, 145, 144, 0.0131, 10122, 9846, 0.8971),
 ('2020', 5418, 70, 70, 0.0129, 5010, 4876, 0.9),
 ('2013', 14542, 165, 164, 0.0113, 13648, 13283, 0.9134),
 ('2005', 11731, 133, 132, 0.0113, 10798, 10472, 0.8927),
 ('2015', 13958, 158, 154, 0.011, 13018, 12664, 0.9073),
 ('2007', 11781, 125, 124, 0.0105, 10878, 10589, 0.8988),
 ('2003', 12204, 127, 124, 0.0102, 11189, 10548, 0.8643),
 ('2014', 14285, 144, 142, 0.0099, 13428, 13042, 0.913),
 ('2008', 13079, 132, 130, 0.0099, 12082, 11760, 0.8992),
 ('2004', 12452, 125, 123, 0.0099, 11409, 11092, 0.8908),
 ('2012', 15276, 153, 147, 0.0096, 14303, 13920, 0.9112),
 ('2011', 15041, 142, 140, 0.0093, 13970, 13605, 0.9045),
 ('2002', 12355, 120, 115, 0.0093, 11324, 10344, 0.8372),
 ('2001', 12720, 122, 116, 0.0091, 11716, 11412, 0.8972),
 ('2009', 13445, 109, 107, 0.008, 12350, 12042, 0.8956),
 ('2010', 13966, 111, 110, 0.0079, 13030, 12653, 0.906)]

The deadliest year for bicycle collisions (in terms of the rate of fatalities) was 2018. Most collisions (> 90%) result in injury of the cyclist(s), but some of that might come from bias of the dataset. The police are more likely to be notified when accidents are more severe.

How severe are bicycle collisions?

In [39]:
%sql SELECT collision_severity, \
    SUM(bicycle_collision) as n_bike_collisions, \
    ROUND(SUM(bicycle_collision) * 1.0 / 252023, 4) AS rate \
FROM collisions \
WHERE bicycle_collision = 1 AND Collision_Date <= '2020-12-31' \
GROUP BY collision_severity \
ORDER BY n_bike_collisions DESC;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[('other injury', 118113, 0.4687),
 ('pain', 90389, 0.3587),
 ('property damage only', 23307, 0.0925),
 ('severe injury', 17478, 0.0694),
 ('fatal', 2736, 0.0109)]

Compare totals for collisions and parties tables

In [4]:
%sql select sum(collisions.bicycle_collision), \
(select count(parties.party_type) \
from parties \
where party_type = 'bicyclist') as sum_party_type \
from collisions;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(252023, 256305)]

Since the number of bicycle collisions is less than the number of parties involving bicyclists, it seems like over 4,000 collisions since 2001 involved more than one cyclist.

How many crashes involved bicycles but no cars?

In [31]:
#collisions with motor vehicle and bicycle:

%sql SELECT COUNT(*) FROM collisions \
        WHERE motor_vehicle_involved_with = 'bicycle';

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(222476,)]

In [27]:
# number of all bike collisions minus collisions with bike and motor vehicle

%sql SELECT \
    (SELECT SUM(bicycle_collision) FROM collisions) - \
    (SELECT COUNT(*) FROM collisions \
        WHERE motor_vehicle_involved_with = 'bicycle') as bike_no_car;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(29547,)]

In [32]:
# view examples of bike_no_car

%sql SELECT * FROM collisions \
        WHERE bicycle_collision = 1 AND \
        motor_vehicle_involved_with != 'bicycle' \
        Limit 5;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[('3526265', 5600, '3364', None, '5', '6', '5607', '0', '0', 'not chp', None, 'not chp', None, 'THOUSAND OAKS BL', 'MAEGAN PL', 2.0, 'west', 0, 'clear', None, 0, None, None, None, None, None, None, None, None, None, 1, 'pain', 0, 1, 2, 'vehicle code violation', None, 'dui', 23152, 'A', 'not hit and run', 'hit object', 'fixed object', 'no pedestrian involved', 'dry', 'normal', None, 'dark with street lights', 'none', '0', None, 1, None, None, 1, 1, 'passenger car', '01', 0, 0, 1, 0, 0, 0, 1, 0, 0, None, None, None, None, '2008-01-03', '17:50:00', '2008-08-13'),
 ('3526312', 3009, '9207', '136', '5', '6', '3009', '0', '0', 'not chp', None, 'not chp', '00R', 'HARBOR BL', 'QUATRO AV', 345.0, 'north', 0, 'clear', None, 0, None, None, None, None, None, None, None, None, None, 1, 'other injury', 0, 1, 7, 'vehicle code violation', None, 'dui', 23152, 'A', 'not hit and run', 'rear end', 'other motor vehicle', 'no pedestrian involved', 'dry', 'normal', None, 'dark with street lights', 'obscured', '0', None, 1, None, None, 1, 1, 'passenger car', '01', 0, 1, 0, 0, 0, 0, 1, 0, 0, None, None, None, None, '2008-01-01', '00:40:00', '2008-08-14'),
 ('3560150', 4316, '10329', '28', '5', '6', '4316', '0', '0', 'not chp', None, 'not chp', '002', 'CENTRAL EXPWY', 'FAIROAKS AV', 528.0, 'west', 0, 'cloudy', None, 0, None, None, None, None, None, None, None, None, None, 0, 'other injury', 0, 1, 1, 'vehicle code violation', None, 'speeding', 22350, None, 'not hit and run', 'hit object', 'fixed object', 'no pedestrian involved', 'wet', 'normal', None, 'daylight', 'none', '0', None, 1, None, None, 1, None, 'bicycle', '04', 0, 1, 0, 0, 0, 0, 1, 0, 0, None, None, None, None, '2008-01-10', '15:42:00', '2008-08-11'),
 ('3565150', 3019, '1839', None, '5', '7', '3019', '0', '0', 'not chp', None, 'not chp', None, 'SUNFLOWER AV', 'FAIRVIEW RD', 0.0, None, 1, 'clear', None, 0, None, None, None, None, None, None, None, None, None, 0, 'pain', 0, 1, 2, 'vehicle code violation', None, 'traffic signals and signs', 21453, 'A', 'not hit and run', 'pedestrian', 'other motor vehicle', 'no pedestrian involved', 'dry', 'normal', None, 'daylight', 'functioning', '0', None, 1, None, None, 1, None, None, None, 0, 0, 1, 0, 0, 0, 1, 0, 0, None, None, None, None, '2008-01-01', '09:28:00', '2008-08-11'),
 ('3565192', 5001, '627', None, '5', '4', '5001', '0', '0', 'not chp', None, 'not chp', '001', 'RICHLAND AV', 'HATCH RD', 0.0, None, 1, 'cloudy', 'raining', 0, None, None, None, None, None, None, None, None, None, 0, 'pain', 0, 1, 2, 'vehicle code violation', None, 'traffic signals and signs', 21453, 'A', 'felony', 'broadside', 'pedestrian', 'no pedestrian involved', 'wet', 'normal', None, 'daylight', 'functioning', '0', None, 1, None, None, 1, 1, 'passenger car', None, 0, 0, 1, 0, 0, 0, 1, 0, 0, None, None, None, None, '2008-01-10', '08:13:00', '2008-08-13')]

On what days of the week do most bicycle collisions occur?

In [27]:
%sql SELECT SUM(bicycle_collision), \
    CASE WHEN strftime('%w', collision_date) = '0' THEN 'Sunday' \
    WHEN strftime('%w', collision_date) = '1' THEN 'Monday' \
    WHEN strftime('%w', collision_date) = '2' THEN 'Tuesday' \
    WHEN strftime('%w', collision_date) = '3' THEN 'Wednesday' \
    WHEN strftime('%w', collision_date) = '4' THEN 'Thursday' \
    WHEN strftime('%w', collision_date) = '5' THEN 'Friday' \
    ELSE 'Saturday' END AS day_of_week \
from collisions \
WHERE bicycle_collision = 1 AND Collision_Date <= '2020-12-31' \
GROUP BY day_of_week \
ORDER BY SUM(bicycle_collision) DESC;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(40133, 'Wednesday'),
 (39969, 'Tuesday'),
 (39571, 'Thursday'),
 (39169, 'Friday'),
 (36594, 'Monday'),
 (31174, 'Saturday'),
 (25413, 'Sunday')]

More collisions occur in the middle of the week, perhaps because more people are out on the road then.

During which months of the year do most bicycle collisions occur?

In [29]:
%sql SELECT SUM(bicycle_collision), \
    CASE WHEN strftime('%m', collision_date) = '01' THEN 'Jan' \
    WHEN strftime('%m', collision_date) = '02' THEN 'Feb' \
    WHEN strftime('%m', collision_date) = '03' THEN 'Mar' \
    WHEN strftime('%m', collision_date) = '04' THEN 'Apr' \
    WHEN strftime('%m', collision_date) = '05' THEN 'May' \
    WHEN strftime('%m', collision_date) = '06' THEN 'Jun' \
    WHEN strftime('%m', collision_date) = '07' THEN 'Jul' \
    WHEN strftime('%m', collision_date) = '08' THEN 'Aug' \
    WHEN strftime('%m', collision_date) = '09' THEN 'Sep' \
    WHEN strftime('%m', collision_date) = '10' THEN 'Oct' \
    WHEN strftime('%m', collision_date) = '11' THEN 'Nov' \
    ELSE 'Dec' END AS day_of_week \
from collisions \
WHERE bicycle_collision = 1 AND Collision_Date <= '2020-12-31' \
GROUP BY day_of_week \
ORDER BY SUM(bicycle_collision) DESC;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(24849, 'Sep'),
 (24205, 'Oct'),
 (23636, 'Jul'),
 (23443, 'Aug'),
 (23130, 'May'),
 (22992, 'Jun'),
 (20906, 'Apr'),
 (20348, 'Mar'),
 (18933, 'Nov'),
 (17210, 'Feb'),
 (17188, 'Jan'),
 (15183, 'Dec')]

What types of weather conditions correlate with collisions involving bicycles?

In [37]:
%sql SELECT weather_1, \
SUM(bicycle_collision) \
FROM collisions \
WHERE bicycle_collision = 1 AND Collision_Date <= '2020-12-31' \
GROUP BY weather_1 \
ORDER BY SUM(bicycle_collision) DESC;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[('clear', 222256),
 ('cloudy', 23463),
 ('raining', 3661),
 (None, 1768),
 ('fog', 482),
 ('other', 272),
 ('wind', 81),
 ('snowing', 40)]

Unsurprisingly, the fewest accidents occur on snowy days, probably because fewer people are cycling then. Similarly, more people are out on clear days and in warmer months, increasing the chances of collision.

How often are cyclists the party at fault?

Each year:

In [ ]:
#%sql SELECT strftime('%Y', collision_date) AS year, \
#    count(distinct collisions.case_id) as n_bike_collisions, \
#    SUM(CASE WHEN statewide_vehicle_type = 'bicycle' AND at_fault = 1 THEN 1 ELSE null END) as n_bike_at_fault, \
#    ROUND(SUM(CASE WHEN statewide_vehicle_type = 'bicycle' AND at_fault = 1 THEN 1 ELSE null END) * 1.0 / count(distinct collisions.case_id), 4) as rate_bike_at_fault \
#FROM collisions \
#LEFT JOIN parties \
#ON collisions.case_id = parties.case_id \
#WHERE bicycle_collision = 1 AND \
#    Collision_Date <= '2020-12-31'\
#GROUP BY year;

In [25]:
%sql SELECT strftime('%Y', collision_date) AS year, \
    count(distinct collisions.case_id) as n_bike_collisions, \
    SUM(CASE WHEN statewide_vehicle_type_at_fault = 'bicycle' THEN 1 ELSE null END) as n_bike_at_fault, \
    ROUND(SUM(CASE WHEN statewide_vehicle_type_at_fault = 'bicycle' THEN 1 ELSE null END) * 1.0 / count(distinct collisions.case_id), 4) as prop_bike_at_fault \
FROM collisions \
WHERE bicycle_collision = 1 AND \
    Collision_Date <= '2020-12-31'\
GROUP BY year;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[('2001', 12720, 7568, 0.595),
 ('2002', 12355, 5945, 0.4812),
 ('2003', 12204, 6406, 0.5249),
 ('2004', 12452, 7192, 0.5776),
 ('2005', 11731, 6656, 0.5674),
 ('2006', 10975, 6064, 0.5525),
 ('2007', 11781, 6601, 0.5603),
 ('2008', 13079, 7312, 0.5591),
 ('2009', 13445, 7556, 0.562),
 ('2010', 13966, 7931, 0.5679),
 ('2011', 15041, 8643, 0.5746),
 ('2012', 15276, 8823, 0.5776),
 ('2013', 14542, 8204, 0.5642),
 ('2014', 14285, 7845, 0.5492),
 ('2015', 13958, 7530, 0.5395),
 ('2016', 13039, 7040, 0.5399),
 ('2017', 12398, 6631, 0.5348),
 ('2018', 12166, 6521, 0.536),
 ('2019', 11192, 5893, 0.5265),
 ('2020', 5418, 2842, 0.5245)]

In total:

In [24]:
%sql SELECT count(distinct collisions.case_id) as n_bike_collisions, \
    SUM(CASE WHEN statewide_vehicle_type_at_fault = 'bicycle' THEN 1 ELSE null END) as n_bike_at_fault, \
    ROUND(SUM(CASE WHEN statewide_vehicle_type_at_fault = 'bicycle' THEN 1 ELSE null END) * 1.0 / count(distinct collisions.case_id), 4) as prop_bike_at_fault \
FROM collisions \
WHERE bicycle_collision = 1 AND \
    Collision_Date <= '2020-12-31';

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(252023, 139203, 0.5523)]

Interestingly, cyclists seem to be at fault more than half of the time, even when I break down the data year by year. This is somewhat surprising, since in accidents involving a bike-on-car collision, liability would likely be allocated to the driver because of the lack of protection afforded to cyclists. 

Could the higher rate of at-fault-cyclists be because cyclists are more often reckless? Or perhaps because they are more often too injured to give their perspective in police reports? The data doesn't provide info on who filed reports, but we can look at the categories of collision types as well as what kind of injuries at-fault-cyclists sustained.

If we look at severe injuries:

In [33]:
%sql SELECT SUM(bicycle_collision) as n_bike_collisions, \
    SUM(severe_injury_count) as n_severe_injury, \
    ROUND(SUM(severe_injury_count) * 1.0 / SUM(bicycle_collision), 4) AS prop \
FROM collisions \
WHERE bicycle_collision = 1 AND statewide_vehicle_type_at_fault = 'bicycle' AND Collision_Date <= '2020-12-31';

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(139203, 10357, 0.0744)]

Severe injuries were reported in only 7% of cases where a bicycle was at fault, so it doesn't seem like injury is biasing the data.

In [37]:
%sql SELECT type_of_collision, \
    SUM(bicycle_collision) as n_bike_collisions, \
    ROUND(SUM(bicycle_collision) * 1.0 / ( \
        SELECT count(*) \
        FROM collisions \
        WHERE bicycle_collision = 1 \
        AND Collision_Date <= '2020-12-31' AND statewide_vehicle_type_at_fault = 'bicycle' \
    ), 4) AS prop \
FROM collisions \
WHERE bicycle_collision = 1 AND Collision_Date <= '2020-12-31' AND statewide_vehicle_type_at_fault = 'bicycle' \
GROUP BY type_of_collision \
ORDER BY n_bike_collisions DESC;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[('broadside', 66031, 0.4744),
 ('other', 35007, 0.2515),
 ('sideswipe', 10356, 0.0744),
 ('head-on', 6689, 0.0481),
 ('rear end', 4965, 0.0357),
 ('pedestrian', 4885, 0.0351),
 ('hit object', 4401, 0.0316),
 ('overturned', 4034, 0.029),
 (None, 2835, 0.0204)]

"Broadside" is the most common type of collision for accidents where the vehicle at fault is a bicycle.

In [38]:
%sql SELECT pcf_violation_category, \
    SUM(bicycle_collision) as n_bike_collisions, \
    ROUND(SUM(bicycle_collision) * 1.0 / ( \
        SELECT count(*) \
        FROM collisions \
        WHERE bicycle_collision = 1 \
        AND Collision_Date <= '2020-12-31' AND statewide_vehicle_type_at_fault = 'bicycle' \
    ), 4) AS prop \
FROM collisions \
WHERE bicycle_collision = 1 AND Collision_Date <= '2020-12-31' AND statewide_vehicle_type_at_fault = 'bicycle' \
GROUP BY pcf_violation_category \
ORDER BY n_bike_collisions DESC;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[('wrong side of road', 53683, 0.3856),
 ('automobile right of way', 21768, 0.1564),
 ('traffic signals and signs', 15919, 0.1144),
 ('improper turning', 13186, 0.0947),
 ('speeding', 11775, 0.0846),
 ('other hazardous violation', 5356, 0.0385),
 (None, 3731, 0.0268),
 ('dui', 3093, 0.0222),
 ('other improper driving', 2470, 0.0177),
 ('unsafe lane change', 1823, 0.0131),
 ('pedestrian violation', 1684, 0.0121),
 ('improper passing', 1389, 0.01),
 ('lights', 879, 0.0063),
 ('unknown', 706, 0.0051),
 ('following too closely', 600, 0.0043),
 ('unsafe starting or backing', 356, 0.0026),
 ('brakes', 312, 0.0022),
 ('pedestrian right of way', 299, 0.0021),
 ('other equipment', 81, 0.0006),
 ('impeding traffic', 65, 0.0005),
 ('other than driver (or pedestrian)', 19, 0.0001),
 ('hazardous parking', 7, 0.0001),
 ('fell asleep', 2, 0.0)]

Driving on the wrong side of the road (39%) and automobile right of way (15%) are the two most common violation categories for cases where bicycles are at fault. So it might be that cyclists are slightly more reckless than drivers. Cycling in the wrong direction is a logical explanation for collisions in areas that are not very bike friendly.

In [39]:
%sql SELECT pcf_violation_category, \
    SUM(bicycle_collision) as n_bike_collisions, \
    ROUND(SUM(bicycle_collision) * 1.0 / ( \
        SELECT count(*) \
        FROM collisions \
        WHERE bicycle_collision = 1 \
        AND Collision_Date <= '2020-12-31' AND statewide_vehicle_type_at_fault != 'bicycle' \
    ), 4) AS prop \
FROM collisions \
WHERE bicycle_collision = 1 AND Collision_Date <= '2020-12-31' AND statewide_vehicle_type_at_fault != 'bicycle' \
GROUP BY pcf_violation_category \
ORDER BY n_bike_collisions DESC;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[('automobile right of way', 23534, 0.3552),
 ('improper turning', 13850, 0.209),
 ('other hazardous violation', 6259, 0.0945),
 ('traffic signals and signs', 5158, 0.0778),
 ('speeding', 3940, 0.0595),
 ('unsafe starting or backing', 2328, 0.0351),
 ('pedestrian right of way', 2275, 0.0343),
 ('improper passing', 1700, 0.0257),
 ('wrong side of road', 1597, 0.0241),
 ('dui', 1236, 0.0187),
 ('unsafe lane change', 982, 0.0148),
 (None, 967, 0.0146),
 ('unknown', 876, 0.0132),
 ('pedestrian violation', 610, 0.0092),
 ('following too closely', 383, 0.0058),
 ('other improper driving', 370, 0.0056),
 ('impeding traffic', 84, 0.0013),
 ('other equipment', 33, 0.0005),
 ('hazardous parking', 32, 0.0005),
 ('lights', 21, 0.0003),
 ('brakes', 16, 0.0002),
 ('other than driver (or pedestrian)', 4, 0.0001),
 ('pedestrian dui', 1, 0.0)]

On the other hand, automobile right of way (35%) was the most common violation category in cases where the vehicle at fault was NOT a bicycle, so this category might not provide much information on how cyclists behave.

In [28]:
%sql SELECT collisions.case_id, strftime('%Y', collision_date) AS year, killed_victims, injured_victims, \
    party_count, pcf_violation_category, type_of_collision, motor_vehicle_involved_with, \
    bicycle_collision, statewide_vehicle_type_at_fault, severe_injurty_count, \
    victim_role, victim_degree_of_injury, \
    parties.id as party_id, party_type, at_fault, other_associate_factor_1 \
FROM collisions \
INNER JOIN victims \
ON collisions.case_id = victims.case_id \
INNER JOIN parties \
ON collisions.case_id = parties.case_id \
WHERE bicycle_collision = 1 AND \
    Collision_Date <= '2020-12-31'\
LIMIT 5;

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[('3526265', '2008', 0, 1, 2, 'dui', 'hit object', 'fixed object', 1, 'passenger car', '4', 'complaint of pain', 3389, 'driver', 1, 'A'),
 ('3526265', '2008', 0, 1, 2, 'dui', 'hit object', 'fixed object', 1, 'passenger car', '4', 'complaint of pain', 3390, 'bicyclist', 0, 'A'),
 ('3526312', '2008', 0, 1, 7, 'dui', 'rear end', 'other motor vehicle', 1, 'passenger car', '4', 'other visible injury', 3468, 'driver', 1, 'A'),
 ('3526312', '2008', 0, 1, 7, 'dui', 'rear end', 'other motor vehicle', 1, 'passenger car', '4', 'other visible injury', 3469, 'driver', 0, 'N'),
 ('3526312', '2008', 0, 1, 7, 'dui', 'rear end', 'other motor vehicle', 1, 'passenger car', '4', 'other visible injury', 3470, 'bicyclist', 0, 'N')]

In [7]:
%sql SELECT count(*) \
FROM collisions \
INNER JOIN victims \
ON collisions.case_id = victims.case_id \
INNER JOIN parties \
ON collisions.case_id = parties.case_id \
WHERE at_fault = 1 AND \
    victim_role = 4 AND \
    bicycle_collision = 1 AND \
    Collision_Date <= '2020-12-31';

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(202694,)]

In [9]:
%sql SELECT count(distinct collisions.case_id) \
FROM collisions \
INNER JOIN victims \
ON collisions.case_id = victims.case_id \
INNER JOIN parties \
ON collisions.case_id = parties.case_id \
WHERE at_fault = 1 AND \
    victim_role = 4 AND \
    bicycle_collision = 1 AND \
    Collision_Date <= '2020-12-31';

 * sqlite:///C://Users//rache//Downloads//data_science//ca-traffic-collisions/switrs.sqlite
Done.

[(200681,)]

**Oustanding questions**

Difference between the sexes? Party at fault or victim?

Differences between age groups? Party at fault or victim?

Where do most bicycle collisions take place? Population-wise.